<?php
$diensten = [
    [
        "dienst" => "Tuinontwerp",
        "img" => "/public/assets/img/tuinontwerp1.jpg",
        "icon" => "/public/assets/img/tuinontwerp_icon.png",
        "id" => "1",
        "tekst" => "Een mooie tuin valt of staat bij een goed tuinontwerp. Als het op ontwerpen aankomt, maakt Hendrik Hogendijk het verschil.",
        "cycleImage1" => "/public/assets/img/tuinontwerp_image1.webp",
        "cycleImage2" => "/public/assets/img/tuinontwerp_image2.webp",
        "cycleImage3" => "/public/assets/img/tuinontwerp_image3.jpg",
    ],
    [
        "dienst" => "Tuinonderhoud",
        "img" => "/public/assets/img/tuinonderhoud1.png",
        "icon" => "/public/assets/img/tuinonderhoud_icon.png",
        "id" => "2",
        "tekst" => "Een mooie tuin verdient het juiste onderhoud. Immers, goed onderhoud is een essentiële voorwaarde voor een tuin die het hele jaar door mooi blijft.",
        "cycleImage1" => "/public/assets/img/tuinonderhoud_image1.jpg",
        "cycleImage2" => "/public/assets/img/tuinonderhoud_image2.jpg",
        "cycleImage3" => "/public/assets/img/tuinonderhoud_image3.jpg",
    ],
    [
        "dienst" => "Zwemvijver",
        "img" => "/public/assets/img/tuinzwemvijver1.jpg",
        "icon" => "/public/assets/img/zwemvijver_icon.png",
        "id" => "3",
        "tekst" => "Zwemvijvers, is één van mijn grootste passies. En gelukkig, ze winnen aan steeds meer populariteit, waardoor ik er veel ervaring mee heb opgebouwd.",
        "cycleImage1" => "/public/assets/img/zwemvijver_image1.jpg",
        "cycleImage2" => "/public/assets/img/zwemvijver_image2.jpg",
        "cycleImage3" => "/public/assets/img/zwemvijver_image3.jpg",
    ],
    [
        "dienst" => "Tuinaanleg",
        "img" => "/public/assets/img/tuinaanleg1.jpg",
        "icon" => "/public/assets/img/tuinaanleg_icon.png",
        "id" => "4",
        "tekst" => "Het aanleggen van een tuin doen ik altijd vanuit dezelfde drive: ik wil er iets moois van maken.",
        "cycleImage1" => "/public/assets/img/tuinaanleg_image1.jpg",
        "cycleImage2" => "/public/assets/img/tuinaanleg_image2.jpg",
        "cycleImage3" => "/public/assets/img/tuinaanleg_image3.jpg",
    ],
];